### ISSUE TITLE
Can you add an example of how to test with a downloaded resource bundle?

### ISSUE THREAD

**Issue by djangofan** [phrase/phraseapp-spring-example#4]
Can you add an example of how to test with a downloaded resource bundle?

Assuming an application that downloads a resource bundle from Phrase, can you provide a recommended pattern for testing the UI ?

Basically, the integration tests would need to be able to compare a "known value" from the downloaded file  with what actually is rendered on the app?

**Comment by theSoenke** [comment]
Hi @djangofan, this repository is an example for the integration of our [InContext-Editor](https://help.phrase.com/help/set-up-in-context-editor). So this would typically be used in a staging environment or something similar to view and edit the translations in the context of the website. 

Still in case when you are downloading the resource files from Phrase for your project I don't think testing will be any different if I'm understanding this issue correctly?

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact [support@phrase.com](mailto:support@phrase.com?subject=[GitHub]%20) and we can take more direct action toward finding a solution.
